# Generated by Django 3.0.8 on 2020-09-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_date',
            new_name='date_joined',
        ),
    ]
