# Generated by Django 3.0.8 on 2020-08-30 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20200828_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
    ]
